apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: demo
spec:
  type: NodePort
  ports:
    - name: demo
      port: 8080
      targetPort: 8080
      nodePort: 30998
  selector:
    app: demo
